# Generated by Django 3.2.6 on 2021-08-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('contact', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
