# Generated by Django 3.2.6 on 2021-08-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypageapp', '0002_employee_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('true', 'ACTIVE'), ('false', 'IN ACTIVE')], default='false', max_length=8),
        ),
    ]
